version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ietpsql
      POSTGRES_PASSWORD: ietlab25
      POSTGRES_DB: iot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iot-network
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ietmdb
      MONGO_INITDB_ROOT_PASSWORD: ietlab25
      MONGO_INITDB_DATABASE: iot_db
    volumes:
      - mongodata:/data/db
    networks:
      - iot-network
    ports:
      - "27017:27017"
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@iotroot.com
      PGADMIN_DEFAULT_PASSWORD: ietlab25
    ports:
      - "5050:80"
    networks:
      - iot-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks:
      - iot-network

volumes:
  pgdata:
  mongodata:
  pgadmin_data:

networks:
  iot-network:
    driver: bridge
